# This runfile solves the assigning engineering students to
# DTC project teams question 2
#
# Group: Jessie Lanin, Victor Agaba, Emily Wei

reset;

# Start the log file
option log_file Question2.log;

# Load the model
model Question2.mod;
data Question2.dat;

# Choose solver and solve
option solver cplex;
solve;

# Display optimal solution 
display s;
display major_proportion;

# Stop the log_file
option log_file '';
close;