# This runfile solves the assigning of engineering students to
# DTC project teams - Phase 2 question 3
#
# Group: Jessie Lanin, Victor Agaba, Emily Wei

reset;

# Start the log file
option log_file Question3.log;

# Load the model
model Question3.mod;
data Question3.dat;

# Choose solver and solve
option solver cplex;
solve;

# Display optimal solution 
display s;
display ConflictofInterest;

# Stop the log_file
option log_file '';
close;